Fix small bug

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 if ! which roundup  >/dev/null; then
-   echo "Error! Whereis no roundup (https://github.com/bmizerany/roundup/)" >&2
+   echo "Error! Where is no roundup (https://github.com/bmizerany/roundup/)" >&2
    exit 1
 fi
 
